version: "3.3"
services:
  the-deadsafe:
    image: ghcr.io/majortom327/deadsafe-landing:main
    # build:
    #   dockerfile: Dockerfile
    #   context: .
    restart: always
    environment:
      - NODE_ENV=production

  docs:
    image: ghcr.io/majortom327/deadsafe-doc:main
    restart: always

  caddy:
    image: caddy:latest
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
    environment:
      - ACME_AGREE=true
      - CADDYPATH=/data/caddy
      - TZ=France/Paris
