version: "3.7"
services:
  the-deadsafe:
    image: the-deadsafe:latest
    context:
      dockerfile: Dockerfile
      context: .
    restart: always
    environment:
      - NODE_ENV=production
    ports:
      - "3000:3000"
