version: "3.3"
services:
  the-deadsafe:
    image: ghcr.io/majortom327/deadsafe-landing:main
    build:
      dockerfile: Dockerfile
      context: .
    restart: always
    environment:
      - NODE_ENV=production
    ports:
      - "4000:3000"
